# Pandas
## Series
- A Pandas Series is a one dimensional labelled array in pandas that is able to store any data type.
- The index of a Series is defined as a list of axis labels. The Index must be of the same length as the data field.
- For Example:
```
data = [1,2,3]
s = pd.Series(data,index=["a","b","c"]) 

```

In [1]:
import numpy as np
import pandas as pd 

arr = np.array([1,2,3,4,5])
s = pd.Series(arr, index=["a","b","c","d","e"])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

## Creating Series from a Dictionary
- When we try to pass pd.Series(<dict>), our Series uses the keys as index and the values of dictionary as the values in the Series.

In [2]:
dict = {
    "January": 120,
    "February": 121,
    "March": 122,
    "April": 123,
    "May": 124
}

series_dict = pd.Series(dict)
print(series_dict)

January     120
February    121
March       122
April       123
May         124
dtype: int64

# Data Frames in Pandas
- Data Frames act as multi dimensional tables that can hold heterogeneous data in Pandas

In [3]:
# Creating a Data Frame by using a Dictionary.

arr1 = np.array(["Saksham","Abhay","Vishal","Yuvraj"])
arr2 = np.array(["Chicago","Washington DC","Seattle","California"])
arr3 = np.array(["Man City","Man United","Arsenal","Liverpool"])

dict = {
    "Names": arr1,
    "Cities": arr2,
    "Football Teams": arr3 
}

df = pd.DataFrame(dict)
df.head()

     Names         Cities Football Teams
0  Saksham        Chicago       Man City
1    Abhay  Washington DC     Man United
2   Vishal        Seattle        Arsenal
3   Yuvraj     California      Liverpool

In [4]:
teams = np.array(["PSG","Man City","Man United","Chelsea"], dtype=np.str_)

psg=np.array(["Dmbele","Mbappe","Lionel Messi","Sergio Ramos"], dtype=np.str_)
man_city=np.array(["Erling Haaland","Duko","Foden","Kevin De Bruyne"], dtype=np.str_)
man_united=np.array(["Paul Pogba","David de Gea","jdfk","dsfk"], dtype=np.str_)
chelsea=np.array(["Eden Hazard","sdfh","sdfh","sdfh"], dtype=np.str_)

members = np.array([psg,man_city,man_united,chelsea], dtype=object)


data = {
    "team_name": teams,
    "players" : [list(x) for x in members],

}

df = pd.DataFrame(data) 
df.head()

    team_name                                         players
0         PSG    [Dmbele, Mbappe, Lionel Messi, Sergio Ramos]
1    Man City  [Erling Haaland, Duko, Foden, Kevin De Bruyne]
2  Man United          [Paul Pogba, David de Gea, jdfk, dsfk]
3     Chelsea                 [Eden Hazard, sdfh, sdfh, sdfh]

# Creating a Data Frame using list of dictionaries
- We can you a list of Dictionaries, where each indiviual dictionary acts as a row in the Data Frame.

In [5]:
list = [
    {"Name":"Saksham","Age":22, "city":"New Delhi"},
    {"Name":"Vaibhav","Age": 15, "city":"Bangalore"},
    {"Name":"Ishita","Age": 23, "city":"Madras"}
]

df = pd.DataFrame(list)
df.head()

      Name  Age       city
0  Saksham   22  New Delhi
1  Vaibhav   15  Bangalore
2   Ishita   23     Madras

In [6]:
python = np.array(["Data Science","Data analytics","Machine Learning","AI Engineering"])
cpp = np.array(["Competitive Programming","Game Development","High Frequency Trading","OS Kernels"])
java = np.array(["Major Backend systems","Big data solutions","cloud-native software","Mobile Dev"])

names = np.array(["python","c++","java"], dtype=np.str_)
uses = np.array([python,cpp,java], dtype=np.object_)


data = [
    {
        "language": names,
        "use_case": uses.tolist()
    }
    for name,use in zip(names,uses)
]

df = pd.DataFrame(data)
df.head()

              language                                           use_case
0  [python, c++, java]  [[Data Science, Data analytics, Machine Learni...
1  [python, c++, java]  [[Data Science, Data analytics, Machine Learni...
2  [python, c++, java]  [[Data Science, Data analytics, Machine Learni...

# Difference b/w .loc[] & .iloc[]
- .loc[] helps to search for values by the Row/Column label .
- .iloc[] helps to search for the values by the row/column position.

- Think of a bookshelf:
    - .loc[] answers : **I want the 'Harry Potter' Book in the bookshelf**
    - .iloc[] answers: **I want the 3rd book from the left**s

In [7]:
l1 = np.array([-1,-2,-3,-4,-5], dtype = np.int32)
l2 = np.array([1,2,3,4,5], dtype=np.int32)
l3 = np.array([-6,-7,-8,-9,-10], dtype=np.int32)

mat = pd.DataFrame({
    "Negative": l1,
    "Positive" : l2 
})

print(mat.head())

mat.loc[3]

   Negative  Positive
0        -1         1
1        -2         2
2        -3         3
3        -4         4
4        -5         5

Negative   -4
Positive    4
Name: 3, dtype: int32

In [8]:
names = np.array(["Saksham","Pratibha","Nandini","Aayushi"], dtype=np.str_)
age = np.array([22, 22, 23, 20], dtype=np.int32)
domain = np.array(["Comp. Sci","Commerce","Public Relations","Finance"], dtype=np.str_)

data = pd.DataFrame({
    "name": names,
    "age": age,
    "domain": domain

})

data.head()

       name  age            domain
0   Saksham   22         Comp. Sci
1  Pratibha   22          Commerce
2   Nandini   23  Public Relations
3   Aayushi   20           Finance

In [14]:
def search_name(name: str):
    print(data.loc[data["name"] == name])
    print("\n")


search_name("Saksham")
search_name("Nandini")
search_name("Pratibha")


def print_specific_val(idx, col_name):
    data.at[idx,col_name]


print_specific_val(2,'domain')

      name  age     domain
0  Saksham   22  Comp. Sci


      name  age            domain
2  Nandini   23  Public Relations


       name  age    domain
1  Pratibha   22  Commerce

# df.at[] Vs df.iat[]
- df.at[] is used to retrieve the value of a specific element by giving 2 arguments
    - One is the Row index
    - One is the Column label

- For example:
```
df = pd.DataFrame{
    "name": ["saksham","nandini","aayushi","pratibha"],
    "age": [22,23,21,22],
    "domain": ["comp sci","public relations","finance","commerce"]
}

print(df.at[2,"name"])----> output = nandini
```

- df.iat[] is used to retrieve the value of a specific element by giving the index values for both row and column as arguments.
- For example: 

```
df = pd.DataFrame{
    "name": ["saksham","nandini","aayushi","pratibha"],
    "age": [22,23,21,22],
    "domain": ["comp sci","public relations","finance","commerce"]
}

print(df.at[0,0])----> output = nandini
```

In [20]:
data2 = pd.DataFrame({
    "name": ["saksham","nandini","aayushi","pratibha"],
    "age": [22,23,21,22],
    "domain": ["comp sci","public relations","finance","commerce"]
})

print(data2.at[1,"name"])
print(data2.iat[0,0])

nandini
saksham

In [ ]:
salaries = np.array([10000,20000, 500000, 700000], dtype=np.float32)
rng = np.random.default_rng()

# Adding a new column.
data2["salary"] = np.mean(salaries) + rng.random()
data2

       name  age            domain        salary
0   saksham   22          comp sci  307500.46875
1   nandini   23  public relations  307500.46875
2   aayushi   21           finance  307500.46875
3  pratibha   22          commerce  307500.46875

In [30]:
# Dropping an existing column; Using column's label (axis=1)
data2.drop("salary", axis=1)
# This is not inplace dropping. This means that the column is not dropped permanently. To make this permanent, set inplace=True. 
data2['age'] = data2['age']+5
data2

       name  age            domain        salary
0   saksham   27          comp sci  307500.46875
1   nandini   28  public relations  307500.46875
2   aayushi   26           finance  307500.46875
3  pratibha   27          commerce  307500.46875